spring.application.name=petshop-api

spring.datasource.url=jdbc:postgresql://localhost:5433/petshopdb
spring.datasource.username=postgres
spring.datasource.password=adison13

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html